### ISSUE TITLE
Wheels for alpine/musl

### ISSUE THREAD

**Issue by fredericoschardong** [harfbuzz/uharfbuzz#166]
Some of us out there are using Python on alpine-based systems, which use musl instead of glibc. Thus, we have to build our own wheels everytime.

Can you please add musl-based wheels? It would imensely speed up the build process.

**Comment by anthrotype** [comment]
I suppose we can. I think cibuildwheel produces those by default already, but we disabled because it was taking long and we figured it was less frequently used

https://github.com/harfbuzz/uharfbuzz/blob/bff12e6be78b990ff9a63e7ac8301a5372c57408/pyproject.toml#L12

Can you send a PR to re-enable them and see if it builds successfully? If it doesn't add too much to the build time I'm ok to  add them.
